services:
  db:
    image: mysql:8.0
    container_name: game-club-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gameclub
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "-prootpassword"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .                       # корень проекта
      dockerfile: backend/Dockerfile
    container_name: game-club-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: gameclub
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
      - ./backend/uploads:/app/uploads
    command: >
      sh -c "npm install && npm start"

volumes:
  db_data: